apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: alpine
        image: alpine:3.20 
