apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-labels-namespace
spec:
  rules:
    - name: add-labels-namespace  
      match:
        resources:
          kinds:
            - Namespace
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              monitoring: prometheus