apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-resources-limits
spec:
  validationFailureAction: Enforce
  rules:
    - name: verify-limits
      match:
        resources:
          kinds:
            - Pod
            - Deployment
      validate:
        message: "Falta definir limites de recursos."   
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
                    memory: "?*"