apiVersion: external-secrets.io/v1 #API version for external secrets
kind: ClusterSecretStore #Kubernetes resource type
metadata:
  name: vault-backend #resource name
spec:
  provider:
    vault: #specifies vault as the provider
      server: "http://vault.geradorqrcode-srjm.uk" #the address of your vault instance
      path: "srjm" #KV secrets engine mount path
      version: "v1" #Vault API version
      auth:
        tokenSecretRef:
          name: "vault-policy-token" #Use a secret called vault-token
          key: "token" #Use this key to access the vault token
