apiVersion: external-secrets.io/v1 
kind: ClusterSecretStore 
metadata:
  name: vault-backend 
spec:
  provider:
    vault: 
      server: "http://vault.geradorqrcode-srjm.uk" 
      path: "srjm" 
      version: "v1" 
      auth:
        tokenSecretRef:
          name: "vault-policy-token" 
          key: "token" 
