apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: srjm-pass-test
    creationPolicy: Owner
  data:
    - secretKey: secret1
      remoteRef:
        key: pass-test
        property: secret1
    - secretKey: secret2
      remoteRef:
        key: pass-test
        property: secret2
