apiVersion: v1
data:
  token: aHZzLkNBRVNJUGZuQVZPR0ppcElzWFhsRHpLNUZ0VjBrY21FMEUyLVVYc2s2NE90MzJrOUdoNEtIR2gyY3k1dVMwSXdXVmxFYkRKTWNFRkllbVZOTTBGVWVscG5SVzg=
kind: Secret
metadata:
  name: vault-policy-token
